[package]
name = "resource-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
pathsub="0.1.1"
glob-match="0.2.1"
walkdir="2.5.0"
#serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"